# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('imei', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, choices=[('null', ''), ('SAMSUNG', 'Samsung'), ('NOKIA', 'Nokia'), ('ALCATEL', 'Alcatel'), ('HUAWEI', 'Huawei'), ('SONY', 'Sony'), ('APPLE', 'Apple')], max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('departamento', models.CharField(blank=True, choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('caracteristica', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='foto_celular')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sim', models.CharField(max_length=20)),
                ('operador', models.CharField(blank=True, choices=[('TIGO', 'Tigo'), ('ENTEL', 'Entel'), ('VIVA', 'Viva')], max_length=20)),
                ('plan', models.CharField(blank=True, max_length=50)),
                ('departamento', models.CharField(blank=True, choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='celular',
            name='instancia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Instancia'),
        ),
    ]
