# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celular',
            old_name='departamento',
            new_name='departamento_origen',
        ),
        migrations.RenameField(
            model_name='instancia',
            old_name='departamento',
            new_name='departamento_origen',
        ),
    ]
