# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20170320_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea_IP',
            fields=[
                ('interno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30)),
                ('ip_central', models.CharField(max_length=30)),
                ('permisos', models.CharField(blank=True, choices=[('CELULAR', 'Celular'), ('LOCAL', 'Local'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_IP',
            fields=[
                ('serie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('ATCOM', ''), ('GRANDSTREAM', 'Samsung'), ('CISCO', 'Nokia'), ('AVAYA', 'Alcatel'), ('POLYCOM', 'Polycom'), ('YEALINK', 'Yealink'), ('FANVIL', 'Fanvil')], max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('mac', models.CharField(blank=True, max_length=30)),
                ('departamento_adquisicion', models.CharField(blank=True, choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('caracteristica', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='celular',
            name='departamento_origen',
        ),
        migrations.AddField(
            model_name='celular',
            name='departamento_origenZZZZZ',
            field=models.CharField(blank=True, choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20),
        ),
    ]
