# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20170322_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celular',
            name='departamento_origenZZZZZ',
        ),
        migrations.AddField(
            model_name='celular',
            name='departamento_origen',
            field=models.CharField(blank=True, choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20),
        ),
    ]
