# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_linea_ip_departamento_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('serie', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('HP', 'Hp'), ('DELL', 'Dell'), ('ASUS', 'Asus'), ('ACER', 'Acer'), ('SAMSUNG', 'Samsung'), ('TOSHIBA', 'Toshiba'), ('COMPAQ', 'Compaq'), ('LENOVO', 'Lenovo'), ('MAC', 'Mac')], max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('sistema_operativo', models.CharField(blank=True, choices=[('WIN10', 'Windows 10'), ('WIN8', 'Windows 8'), ('WIN7', 'Windows 7'), ('WINXP', 'Windows XP'), ('MACOS', 'macOS'), ('UBUNTU', 'Ubuntu'), ('DEBIAN', 'Debian'), ('REDHAT', 'Red Hat'), ('MINT', 'Mint')], max_length=20)),
                ('procesador', models.CharField(blank=True, choices=[('WIN10', 'Windows 10'), ('WIN8', 'Windows 8'), ('WIN7', 'Windows 7'), ('WINXP', 'Windows XP'), ('MACOS', 'macOS'), ('UBUNTU', 'Ubuntu'), ('DEBIAN', 'Debian'), ('REDHAT', 'Red Hat'), ('MINT', 'Mint')], max_length=20)),
                ('arquitectura', models.CharField(max_length=40)),
                ('ram', models.CharField(blank=True, choices=[('2', '2 Gb'), ('4', '4 Gb'), ('8', '8 Gb'), ('12', '12 Gb'), ('16', '16 Gb'), ('32', '32 Gb')], max_length=20)),
                ('hdd', models.CharField(blank=True, choices=[('250', '250 Gb'), ('500', '500 Gb'), ('750', '750 Gb'), ('1024', '1 Tb')], max_length=20)),
                ('display', models.CharField(blank=True, choices=[('14', '14 Pulgadas'), ('15', '15 Pulgadas'), ('17', '14 Pulgadas'), ('19', '14 Pulgadas')], max_length=20)),
                ('cargador', models.CharField(max_length=40)),
                ('departamento_adquisicion', models.CharField(blank=True, choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('caracteristica', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
    ]
