# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(help_text='Documento Nacinal de Identidad', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nacionalidad', models.CharField(choices=[('NACIONAL', 'Nacional'), ('EXTRANJERO', 'Extranjero')], max_length=30)),
                ('nit', models.CharField(blank=True, help_text='NIT', max_length=20)),
                ('nombres', models.CharField(help_text='Nombres', max_length=60)),
                ('appaterno', models.CharField(blank=True, help_text='Apellido Parterno', max_length=50)),
                ('apmaterno', models.CharField(blank=True, help_text='Apellido Materno', max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=30)),
                ('correo', models.CharField(blank=True, help_text='Correo Electronico', max_length=50)),
                ('celular', models.CharField(blank=True, help_text='Telefono Fijo', max_length=20)),
                ('fijo', models.CharField(blank=True, help_text='Telefono Celular', max_length=20)),
                ('nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
