# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioncliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField()),
                ('siguiente_interaccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_interaccion', models.CharField(choices=[('IN', 'Esperar'), ('OUT', 'Realizar')], default='OUT', max_length=30)),
                ('interaccion', models.CharField(choices=[('LLAMADA', 'Llamada'), ('VISITA', 'Visita'), ('CORREO', 'Correo'), ('MENSAJE', 'Mensaje'), ('OTRO', 'Otro')], default='LLAMADA', max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioncliente.Oportunidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
