# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='anonimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='dni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
