# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='codigo',
            field=models.CharField(help_text='El codigo de la agencia debe contener 6 digitos Ejemplo: LPZ001', max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
