# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_agencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='agencia',
            name='sim',
        ),
        migrations.AddField(
            model_name='agencia',
            name='ciudad',
            field=models.CharField(choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='codigo',
            field=models.CharField(default=1, help_text='Codigo de la Agencia', max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agencia',
            name='empresa',
            field=models.CharField(choices=[('CROWN', 'Crown'), ('TOYOSA', 'Toyosa'), ('TOYOTA', 'Toyota')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='foto',
            field=models.ImageField(blank=True, help_text='Suba la foto de la Sucursal', upload_to='foto_agencia'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='lat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='lng',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='nombre',
            field=models.CharField(default=1, help_text='Nombre de la Agencia', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='pais',
            field=models.CharField(choices=[('BOLIVIA', 'Bolivia'), ('CHILE', 'Chile'), ('CUBA', 'Cuba'), ('EEUU', 'Estados Unidos')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
