# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170511_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencia',
            old_name='direccion',
            new_name='referencia',
        ),
    ]
