# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculos', models.CharField(choices=[('CAMION', 'Camion'), ('MOTO', 'Moto'), ('VEHICULOLIVIANO', 'Vehiculo Liviano')], max_length=30)),
                ('referencia', models.CharField(choices=[('PERSONAL', 'Personal'), ('REDES', 'Redes'), ('RADIO', 'Radio'), ('VOLANTES', 'Volantes'), ('SHOWROOM', 'Show Room'), ('OTRO', 'Otro')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Agencia')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
