# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '__first__'),
        ('gestioncliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='ficha2',
        ),
        migrations.AddField(
            model_name='visita',
            name='agencia',
            field=models.ForeignKey(default='La Paz', on_delete=django.db.models.deletion.CASCADE, to='usuario.Agencia'),
            preserve_default=False,
        ),
    ]
