# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_auto_20170607_2324'),
        ('cliente', '0001_initial'),
        ('gestioncliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('negociacion', models.TextField()),
                ('modelo_actual', models.CharField(blank=True, max_length=50)),
                ('modelo_interes', models.CharField(blank=True, max_length=50)),
                ('tipo_venta', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito'), ('AUTOFACIL', 'AutoFacil'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EXITOSA', 'Redes'), ('CAIDA', 'Radio'), ('SUSPENDIDA', 'Volantes')], default='VIGENTE', max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Agencia')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('vendedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo_vehiculos',
            field=models.CharField(choices=[('CAMION', 'Camion'), ('MOTO', 'Moto'), ('VEHICULOLIVIANO', 'Vehiculo Liviano')], default='VEHICULOLIVIANO', max_length=30),
        ),
    ]
