# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncliente', '0002_auto_20170607_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('EXITOSA', 'Venta Exitosa'), ('CAIDA', 'Venta Caida'), ('SUSPENDIDA', 'Suspendida Temporalmente')], default='VIGENTE', max_length=30),
        ),
    ]
