# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170523_2009'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioncliente', '0002_auto_20170523_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='departamento_origen',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='visita',
            name='dni',
            field=models.ForeignKey(default=4792347, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='referencia',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('REDES', 'Redes'), ('RADIO', 'Radio'), ('VOLANTES', 'Volantes'), ('SHOWROOM', 'Show Room'), ('OTRO', 'Otro')], default='PERSONAL', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo_vehiculos',
            field=models.CharField(choices=[('CAMION', 'Camion'), ('MOTO', 'Moto'), ('VEHICULOLIVIANO', 'Vehiculo Liviano')], default='MOTO', max_length=30),
            preserve_default=False,
        ),
    ]
