# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioncliente', '0003_auto_20170523_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
