# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nacionalidad', models.CharField(choices=[('BOLIVIANA', 'Boliviana'), ('EXTRANJERO', 'Extranjero')], default='BOLIVIANA', max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('appaterno', models.CharField(blank=True, max_length=50)),
                ('apmaterno', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=50)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('fijo', models.IntegerField(blank=True, null=True)),
                ('nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
