# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apmaterno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='appaterno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(choices=[('BOLIVIANA', 'Boliviana'), ('EXTRANJERO', 'Extranjero')], default='BOLIVIANA', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
