# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.CharField(help_text='Inserte el Codigo de Marca', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='Inserte el Nombre de la Marca', max_length=50, unique=True)),
                ('foto', models.ImageField(help_text='Suba la foto de la Marca', upload_to='')),
                ('garantia', models.IntegerField(blank=True, help_text='Garantia en Años', null=True)),
                ('paginaweb', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
