# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('codigo', models.CharField(help_text='El codigo de la agencia debe contener 6 digitos Ejemplo: LPZ001', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la Agencia', max_length=50, unique=True)),
                ('foto', models.ImageField(help_text='Suba la foto de la Sucursal', upload_to='')),
                ('telefono', models.IntegerField(blank=True, help_text='Telefono de Contacto', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(choices=[('CROWN', 'Crown'), ('TOYOSA', 'Toyosa'), ('TOYOTA', 'Toyota')], max_length=30)),
                ('pais', models.CharField(choices=[('BOLIVIA', 'Bolivia'), ('CHILE', 'Chile'), ('CUBA', 'Cuba'), ('EEUU', 'Estados Unidos')], max_length=30)),
                ('ciudad', models.CharField(choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lng', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lng', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=30)),
                ('nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('cel_corp', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('interno', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(choices=[('GERENTE', 'Gerente'), ('SUBGERENTE', 'Sub Gerente'), ('JEFE', 'Jefe'), ('RESPONSABLE', 'Responsable'), ('ANALISTA', 'Analista'), ('EJECUTIVO', 'Ejecutivo'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecanico'), ('MENSAJERO', 'Mensajero'), ('PASANTE', 'Pasante')], max_length=30)),
                ('area', models.CharField(choices=[('VENTAS', 'Ventas'), ('FINANZAS', 'Finanzas'), ('CARTERA', 'Cartera'), ('MARKETING', 'Marketing'), ('CONTABILIDAD', 'Contabilidad'), ('RRHH', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas'), ('SERVICIOS', 'Servicios'), ('TALLER', 'Taller'), ('LICITACIONES', 'Licitaciones'), ('IMPORTACIONES', 'Importaciones'), ('LEGAL', 'Legal'), ('AGENCIAINTERNA', 'Agencia Interna')], max_length=30)),
                ('foto', models.ImageField(upload_to='')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('BAJATEMP', 'Baja Temporal')], max_length=15)),
                ('afp', models.CharField(blank=True, choices=[('FUTURO', 'Futuro'), ('PREVISION', 'Prevision')], max_length=15)),
                ('nua', models.CharField(blank=True, max_length=20)),
                ('numero_afiliacion', models.CharField(blank=True, max_length=20)),
                ('persona_ref1', models.CharField(blank=True, max_length=50)),
                ('telefono_ref1', models.IntegerField(blank=True, null=True)),
                ('persona_ref2', models.CharField(blank=True, max_length=50)),
                ('telefono_ref2', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Agencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
