# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
