# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_agencia_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='lng',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
